// MyInvois reference code lists, from LHDN's official SDK code tables.
// Used to populate the classification-code and unit-of-measurement selects, and the AI is
// instructed to pick from these when reading a document.

export interface CodeOption {
  value: string;
  label: string;
}

// e-Invoice "Classification" codes (LHDN SDK: Classification).
export const CLASSIFICATION_CODES: CodeOption[] = [
  { value: '001', label: '001 — Breastfeeding equipment' },
  { value: '002', label: '002 — Child care centres and kindergartens fees' },
  { value: '003', label: '003 — Computer, smartphone or tablet' },
  { value: '004', label: '004 — Consolidated e-Invoice' },
  { value: '005', label: '005 — Construction materials' },
  { value: '006', label: '006 — Disbursement' },
  { value: '007', label: '007 — Donation' },
  { value: '008', label: '008 — e-Commerce - e-Invoice to buyer / purchaser' },
  { value: '009', label: '009 — e-Commerce - Self-billed e-Invoice to seller, logistics, etc.' },
  { value: '010', label: '010 — Education fees' },
  { value: '011', label: '011 — Goods on consignment (Consignor)' },
  { value: '012', label: '012 — Goods on consignment (Consignee)' },
  { value: '013', label: '013 — Gym membership' },
  { value: '014', label: '014 — Insurance - Education and medical benefits' },
  { value: '015', label: '015 — Insurance - Takaful or life insurance' },
  { value: '016', label: '016 — Interest and financing expenses' },
  { value: '017', label: '017 — Internet subscription' },
  { value: '018', label: '018 — Land and building' },
  { value: '019', label: '019 — Medical examination for learning disabilities / early intervention' },
  { value: '020', label: '020 — Medical examination or vaccination expenses' },
  { value: '021', label: '021 — Medical expenses for serious diseases' },
  { value: '022', label: '022 — Others' },
  { value: '023', label: '023 — Petroleum operations' },
  { value: '024', label: '024 — Private retirement scheme or deferred annuity scheme' },
  { value: '025', label: '025 — Motor vehicle' },
  { value: '026', label: '026 — Subscription of books / journals / magazines / newspapers' },
  { value: '027', label: '027 — Reimbursement' },
  { value: '028', label: '028 — Rental of motor vehicle' },
  { value: '029', label: '029 — EV charging facilities' },
  { value: '030', label: '030 — Repair and maintenance' },
  { value: '031', label: '031 — Research and development' },
  { value: '032', label: '032 — Foreign income' },
  { value: '033', label: '033 — Self-billed - Betting and gaming' },
  { value: '034', label: '034 — Self-billed - Importation of goods' },
  { value: '035', label: '035 — Self-billed - Importation of services' },
  { value: '036', label: '036 — Self-billed - Others' },
  { value: '037', label: '037 — Self-billed - Monetary payment to agents, dealers or distributors' },
  { value: '038', label: '038 — Sports equipment / facilities / competition / training fees' },
  { value: '039', label: '039 — Supporting equipment for disabled person' },
  { value: '040', label: '040 — Voluntary contribution to approved provident fund' },
  { value: '041', label: '041 — Dental examination or treatment' },
  { value: '042', label: '042 — Fertility treatment' },
  { value: '043', label: '043 — Treatment and home care nursing, daycare / residential care' },
  { value: '044', label: '044 — Vouchers, gift cards, loyalty points, etc' },
  { value: '045', label: '045 — Self-billed - Non-monetary payment to agents, dealers or distributors' },
];

// Unit of Measurement codes (LHDN SDK: UnitType, UN/ECE Rec. 20) — a common working subset.
export const UOM_CODES: CodeOption[] = [
  { value: 'C62', label: 'C62 — Unit (one)' },
  { value: 'H87', label: 'H87 — Piece' },
  { value: 'EA', label: 'EA — Each' },
  { value: 'SET', label: 'SET — Set' },
  { value: 'NPR', label: 'NPR — Pair' },
  { value: 'DZN', label: 'DZN — Dozen' },
  { value: 'KGM', label: 'KGM — Kilogram' },
  { value: 'GRM', label: 'GRM — Gram' },
  { value: 'MGM', label: 'MGM — Milligram' },
  { value: 'TNE', label: 'TNE — Tonne (metric)' },
  { value: 'LTR', label: 'LTR — Litre' },
  { value: 'MLT', label: 'MLT — Millilitre' },
  { value: 'MTR', label: 'MTR — Metre' },
  { value: 'CMT', label: 'CMT — Centimetre' },
  { value: 'MMT', label: 'MMT — Millimetre' },
  { value: 'KMT', label: 'KMT — Kilometre' },
  { value: 'MTK', label: 'MTK — Square metre' },
  { value: 'MTQ', label: 'MTQ — Cubic metre' },
  { value: 'HUR', label: 'HUR — Hour' },
  { value: 'DAY', label: 'DAY — Day' },
  { value: 'WEE', label: 'WEE — Week' },
  { value: 'MON', label: 'MON — Month' },
  { value: 'ANN', label: 'ANN — Year' },
  { value: 'MIN', label: 'MIN — Minute' },
  { value: 'XBX', label: 'XBX — Box' },
  { value: 'XCT', label: 'XCT — Carton' },
  { value: 'XPK', label: 'XPK — Package' },
  { value: 'XBG', label: 'XBG — Bag' },
  { value: 'XBO', label: 'XBO — Bottle' },
  { value: 'XRO', label: 'XRO — Roll' },
  { value: 'XPX', label: 'XPX — Pallet' },
];
